server:
  port: 8081
spring:
  cloud:
    config: 
      server:
        git:
         default-label: eureka
         uri: https://github.com/CamiShofijara32/Microservicios.git
         search-paths: config-data
  application: 
      name: config-service